# Generated by Django 2.2.4 on 2021-01-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='no desc'),
            preserve_default=False,
        ),
    ]
